apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aiot
  name: aiot
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aiot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aiot
    spec:
      containers:
      - image: registry.cn-hongkong.aliyuncs.com/36node/haivivi-aiot
        imagePullPolicy: IfNotPresent
        name: aiot
        ports:
        - containerPort: 9527
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /aiot/v1/hello
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/apps/aiot/access.yaml
          name: access-volume
          subPath: access.yaml
        - mountPath: /app/ssl
          name: ssl-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until curl -sf http://auth/auth/v1/hello; do echo waiting for auth service
          ready; sleep 10; done;
        image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/curl:7.83.1
        imagePullPolicy: IfNotPresent
        name: wait-for-auth
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: config
        name: access-volume
      - name: ssl-volume
        secret:
          defaultMode: 420
          secretName: auth-ssl
