apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal-web
  name: portal-web
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: portal-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portal-web
    spec:
      containers:
      - image: registry.cn-hongkong.aliyuncs.com/36node/haivivi-portal-web
        imagePullPolicy: IfNotPresent
        name: portal-web
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until curl -sf http://auth/auth/v1/hello; do echo waiting for auth service
          ready; sleep 10; done;
        image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/curl:7.83.1
        imagePullPolicy: IfNotPresent
        name: wait-for-auth
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - until curl -sf http://aiot/aiot/v1/hello; do echo waiting for aiot service
          ready; sleep 10; done;
        image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/curl:7.83.1
        imagePullPolicy: IfNotPresent
        name: wait-for-aiot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - until curl -sf http://pal/pal/v1/hello; do echo waiting for pal service
          ready; sleep 10; done;
        image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/curl:7.83.1
        imagePullPolicy: IfNotPresent
        name: wait-for-pal
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - until curl -sf http://palapp/palapp/v1/hello; do echo waiting for palapp
          service ready; sleep 10; done;
        image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/curl:7.83.1
        imagePullPolicy: IfNotPresent
        name: wait-for-palapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - until curl -sf http://pms/pms/v1/hello; do echo waiting for pms service
          ready; sleep 10; done;
        image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/curl:7.83.1
        imagePullPolicy: IfNotPresent
        name: wait-for-pms
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - until curl -sf http://portal/portal/v1/hello; do echo waiting for portal
          service ready; sleep 10; done;
        image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/curl:7.83.1
        imagePullPolicy: IfNotPresent
        name: wait-for-portal
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

