apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#configMapGenerator:
#  - name: config
#    behavior: create
#    files:
#      - access.yaml
#
#secretGenerator:
#  - name: auth-ssl
#    behavior: create
#    files:
#      - syw-secret.key
#    type: Opaque


generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: auth-ssl
    behavior: create
    files:
      - private.key
      - public.key
    type: Opaque

  - name: stage-env
    envs:
      - stage-env.ini
    type: Opaque