apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haivivi-test
#commonLabels:
#  cluster: prod-asia
#  env: prod

resources:
  - ../../../base/haivivi-test/test-project
#  - ../../../base/haivivi-test/test-ooo
#  - ../../../base/haivivi-test/test-aaa

#components:
#  - ../../../components/cn-stage/


images:
  - name: cn-haivivi-cn-shanghai.cr.volces.com/libiary/nginx
    newTag: latest

patches:
  - path: patches/syw-test-replica.yaml