apiVersion: apps/v1
kind: Deployment
metadata:
  name: syw-test
  labels:
    app: syw-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syw-test
  template:
    metadata:
      name: syw-test
      labels:
        app: syw-test
    spec:
      containers:
        - name: syw-test
          image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /root/ssl
              name: ssl-volume
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssl-volume
          secret:
            defaultMode: 420
            secretName: auth-ssl

