apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#configMapGenerator:
#  - name: config
#    behavior: create
#    files:
#      - access.yaml
#
#secretGenerator:
#  - name: auth-ssl
#    behavior: create
#    files:
#      - syw-secret.key
#    type: Opaque


#generatorOptions:
#  disableNameSuffixHash: true

secretGenerator:
  - name: env-secret
    envs:
      - env-secret.txt
    type: Opaque
  - name: env-secret-file
    envs:
      - env-secret-file.txt
    type: Opaque