apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#configMapGenerator:
#  - name: config
#    behavior: create
#    files:
#      - access.yaml
#
#secretGenerator:
#  - name: auth-ssl
#    behavior: create
#    files:
#      - syw-secret.key
#    type: Opaque


generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: env-secret
    envs:
      - env.ini
    type: Opaque
  - name: literals-secret
    literals:
      - JAVA_HOME=/opt/java/jdk
      - JAVA_TOOL_OPTIONS=-agentlib:hprof
#  - name: yaml-secret
#    files:
#      - secret.yaml
#    type: Opaque
#    options:
#      annotations:
#        app_config: "true"
#      labels:
#        app.kubernetes.io/name: "app2"
#  - name: env-secret-file
#    envs:
#      - secret.example.ini
#    type: Opaque