apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haivivi-advr
#commonLabels:
#  cluster: prod-asia
#  env: prod

resources:                 # ← 决定“发哪些”
  - ../../../base/haivivi-advr/test-project

#components:                # ← 插上“公共补丁”
#  - ../../../components/cn-stage/

patches:                   # ← 本组本环境特殊补丁
  - path: patches/syw-test-replica.yaml