apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#configMapGenerator:
#  - name: config
#    behavior: create
#    files:
#      - access.yaml
#
#secretGenerator:
#  - name: auth-ssl
#    behavior: create
#    files:
#      - syw-secret.key
#    type: Opaque


generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: auth-ssl
    behavior: create
    files:
      - private.key
      - public.key
    type: Opaque
  - name: admin-web-env
    envs:
      - admin-web.ini
    type: Opaque
  - name: aiot-env
    envs:
      - aiot.ini
    type: Opaque
  - name: auth-env
    envs:
      - auth.ini
    type: Opaque
  - name: bull-board-env
    envs:
      - bull-board.ini
    type: Opaque
  - name: pal-env
    envs:
      - pal.ini
    type: Opaque
  - name: palapp-env
    envs:
      - palapp.ini
    type: Opaque
  - name: palgear-env
    envs:
      - palgear.ini
    type: Opaque
  - name: pms-env
    envs:
      - pms.ini
    type: Opaque
  - name: portal-env
    envs:
      - portal.ini
    type: Opaque
  - name: portal-web-env
    envs:
      - portal-web.ini
    type: Opaque
  - name: push-env
    envs:
      - push.ini
    type: Opaque
  - name: www-env
    envs:
      - www.ini
    type: Opaque
